py.install_sources(
  '__init__.py',
  'all.py',
  'attach.py',
  'configuration.py',
  'image.py',
  'inputhook.py',
  'interface_magic.py',
  'interpreter.py',
  'ipython_extension.py',
  'ipython_tests.py',
  'load.py',
  'preparse.py',
  'prompts.py',
  'user_globals.py',
  subdir: 'sage/repl',
)

subdir('display')
subdir('ipython_kernel')
subdir('rich_output')
