py.install_sources(
  '__init__.py',
  'all.py',
  'bitness.py',
  'bliss.py',
  'brial.py',
  'cddlib.py',
  'coxeter3.py',
  'csdp.py',
  'cython.py',
  'databases.py',
  'dot2tex.py',
  'dvipng.py',
  'ecm.py',
  'ffmpeg.py',
  'flatter.py',
  'four_ti_2.py',
  'frobby.py',
  'fricas.py',
  'gap.py',
  'gap3.py',
  'gfan.py',
  'giac.py',
  'graph_generators.py',
  'graphviz.py',
  'igraph.py',
  'imagemagick.py',
  'info.py',
  'interfaces.py',
  'internet.py',
  'jmol.py',
  'join_feature.py',
  'kenzo.py',
  'khoca.py',
  'latex.py',
  'latte.py',
  'lcalc.py',
  'lrs.py',
  'mcqd.py',
  'meataxe.py',
  'meson_editable.py',
  'mip_backends.py',
  'msolve.py',
  'nauty.py',
  'normaliz.py',
  'palp.py',
  'pandoc.py',
  'pari.py',
  'pdf2svg.py',
  'phitigra.py',
  'planarity.py',
  'pkg_systems.py',
  'polymake.py',
  'poppler.py',
  'qepcad.py',
  'rubiks.py',
  'sagemath.py',
  'sat.py',
  'singular.py',
  'sirocco.py',
  'sloane_database.py',
  'sphinx.py',
  'standard.py',
  'symengine_py.py',
  'tdlib.py',
  'threejs.py',
  'tides.py',
  'topcom.py',
  subdir: 'sage/features',
)
