# Sage version information for Python scripts
# This file is auto-generated by the update-version script, do not edit!
version = '10.9.post15'
date = '2026-07-12'
banner = 'SageMath version 10.9.post15, Release Date: 2026-07-12'
