# Sage version information for Python scripts
# This file is auto-generated by the update-version script, do not edit!
version = '10.9.beta9.post4'
date = '2026-04-21'
banner = 'SageMath version 10.9.beta9.post4, Release Date: 2026-04-21'
