# Sage version information for Python scripts
# This file is auto-generated by the update-version script, do not edit!
version = '10.9.post1'
date = '2026-05-04'
banner = 'SageMath version 10.9.post1, Release Date: 2026-05-04'
