doc_sources = [
  'conf.py',
  'index.rst',
  'index_standard.rst',
  'index_optional.rst',
  'index_sagemath.rst',
  'index_experimental.rst',
  'index_alph.rst',
  '4ti2.rst',
  '_bootstrap.rst',
  '_develop.rst',
  '_prereq.rst',
  '_recommended.rst',
  '_sagemath.rst',
  'accessible_pygments.rst',
  'admcycles.rst',
  'alabaster.rst',
  'anyio.rst',
  'appdirs.rst',
  'argon2_cffi.rst',
  'argon2_cffi_bindings.rst',
  'appnope.rst',
  'arrow.rst',
  'asttokens.rst',
  'async_lru.rst',
  'attrs.rst',
  'auditwheel_or_delocate.rst',
  'awali.rst',
  'babel.rst',
  'barvinok.rst',
  'beautifulsoup4.rst',
  'beniget.rst',
  'benzene.rst',
  'biopython.rst',
  'bleach.rst',
  'bliss.rst',
  'brial.rst',
  'buckygen.rst',
  'cachetools.rst',
  'calver.rst',
  'cbc.rst',
  'ccache.rst',
  'cddlib.rst',
  'certifi.rst',
  'cffi.rst',
  'chardet.rst',
  'charset_normalizer.rst',
  'clarabel.rst',
  'cliquer.rst',
  'cmake.rst',
  'cocoalib.rst',
  'colorama.rst',
  'comm.rst',
  'configure.rst',
  'contourpy.rst',
  'conway_polynomials.rst',
  'coxeter3.rst',
  'cppy.rst',
  'csdp.rst',
  'cunningham_tables.rst',
  'curl.rst',
  'cvxopt.rst',
  'cvxpy.rst',
  'cycler.rst',
  'cylp.rst',
  'cypari.rst',
  'cysignals.rst',
  'cython.rst',
  'd3js.rst',
  'database_cremona_ellcurve.rst',
  'database_jones_numfield.rst',
  'database_cubic_hecke.rst',
  'database_knotinfo.rst',
  'database_kohel.rst',
  'database_mutation_class.rst',
  'database_odlyzko_zeta.rst',
  'database_stein_watkins.rst',
  'database_stein_watkins_mini.rst',
  'database_symbolic_data.rst',
  'dateutil.rst',
  'debugpy.rst',
  'decorator.rst',
  'deformation.rst',
  'defusedxml.rst',
  'distlib.rst',
  'docutils.rst',
  'dot2tex.rst',
  'dsdp.rst',
  'e_antic.rst',
  'ecl.rst',
  'eclib.rst',
  'ecm.rst',
  'ecos_python.rst',
  'elliptic_curves.rst',
  'execnet.rst',
  'executing.rst',
  'fastjsonschema.rst',
  'fflas_ffpack.rst',
  'ffmpeg.rst',
  'filelock.rst',
  'flint.rst',
  'flit_core.rst',
  'fonttools.rst',
  'fplll.rst',
  'fpylll.rst',
  'fqdn.rst',
  'free_fonts.rst',
  'freetype.rst',
  'fricas.rst',
  'frobby.rst',
  'furo.rst',
  'gap.rst',
  'gap3.rst',
  'gap_jupyter.rst',
  'gap_packages.rst',
  'gast.rst',
  'gc.rst',
  'gcc.rst',
  'gdb.rst',
  'gengetopt.rst',
  'gf2x.rst',
  'gfan.rst',
  'gfortran.rst',
  'git.rst',
  'giac.rst',
  'github_cli.rst',
  'gitpython.rst',
  'givaro.rst',
  'glpk.rst',
  'glucose.rst',
  'gmp.rst',
  'gmpy2.rst',
  'gnulib.rst',
  'gnumake_tokenpool.rst',
  'gp2c.rst',
  'graphs.rst',
  'graphviz.rst',
  'gsl.rst',
  'h11.rst',
  'hatch_readme.rst',
  'hatch_vcs.rst',
  'hatchling.rst',
  'highspy.rst',
  'httpcore.rst',
  'httpx.rst',
  'hypothesis.rst',
  'iconv.rst',
  'idna.rst',
  'igraph.rst',
  'imagemagick.rst',
  'imagesize.rst',
  'iml.rst',
  'info.rst',
  'iniconfig.rst',
  'ipykernel.rst',
  'ipympl.rst',
  'ipython.rst',
  'ipython_genutils.rst',
  'ipython_pygments_lexers.rst',
  'ipywidgets.rst',
  'isl.rst',
  'isoduration.rst',
  'jedi.rst',
  'jinja2.rst',
  'jmol.rst',
  'joblib.rst',
  'json5.rst',
  'jsonpointer.rst',
  'jsonschema.rst',
  'jsonschema_specifications.rst',
  'jupymake.rst',
  'jupyter_client.rst',
  'jupyter_events.rst',
  'jupyter_core.rst',
  'jupyter_jsmol.rst',
  'jupyter_lsp.rst',
  'jupyter_server.rst',
  'jupyter_server_terminals.rst',
  'jupyter_sphinx.rst',
  'jupyterlab.rst',
  'jupyterlab_mathjax2.rst',
  'jupyterlab_server.rst',
  'jupyterlab_pygments.rst',
  'jupyterlab_widgets.rst',
  'kenzo.rst',
  'khoca.rst',
  'kissat.rst',
  'kiwisolver.rst',
  'latte_int.rst',
  'lcalc.rst',
  'libatomic_ops.rst',
  'libbraiding.rst',
  'libgd.rst',
  'libffi.rst',
  'libgraphviz.rst',
  'libhomfly.rst',
  'libjpeg.rst',
  'libnauty.rst',
  'libogg.rst',
  'libpng.rst',
  'libsemigroups.rst',
  'libxml2.rst',
  'lidia.rst',
  'lie.rst',
  'linbox.rst',
  'llvm.rst',
  'lrcalc.rst',
  'lrcalc_python.rst',
  'lrslib.rst',
  'm4ri.rst',
  'm4rie.rst',
  'markupsafe.rst',
  'mathics.rst',
  'mathjax.rst',
  'matplotlib.rst',
  'matplotlib_inline.rst',
  'matroid_database.rst',
  'maxima.rst',
  'mcqd.rst',
  'meataxe.rst',
  'memory_allocator.rst',
  'meson.rst',
  'meson_python.rst',
  'mistune.rst',
  'modular_resolution.rst',
  'mpc.rst',
  'mpfi.rst',
  'mpfr.rst',
  'mpfrcx.rst',
  'msolve.rst',
  'mpmath.rst',
  'nauty.rst',
  'nbclient.rst',
  'nbconvert.rst',
  'nbformat.rst',
  'ncurses.rst',
  'nest_asyncio.rst',
  'networkx.rst',
  'nibabel.rst',
  'ninja_build.rst',
  'normaliz.rst',
  'notebook.rst',
  'notebook_shim.rst',
  'notedown.rst',
  'numpy.rst',
  'ntl.rst',
  'onetbb.rst',
  'openblas.rst',
  'openssl.rst',
  'ore_algebra.rst',
  'osqp_python.rst',
  'overrides.rst',
  'p_group_cohomology.rst',
  'packaging.rst',
  'palp.rst',
  'pandoc.rst',
  'pandoc_attributes.rst',
  'pandocfilters.rst',
  'papilo.rst',
  'pari.rst',
  'pari_elldata.rst',
  'pari_galdata.rst',
  'pari_galpol.rst',
  'pari_jupyter.rst',
  'pari_nftables.rst',
  'pari_seadata.rst',
  'pari_seadata_small.rst',
  'parso.rst',
  'patchelf.rst',
  'pathspec.rst',
  'pdf2svg.rst',
  'perl_cpan_polymake_prereq.rst',
  'perl_mongodb.rst',
  'perl_term_readline_gnu.rst',
  'pexpect.rst',
  'phitigra.rst',
  'pickleshare.rst',
  'pillow.rst',
  'pip.rst',
  'pkgconfig.rst',
  'planarity.rst',
  'plantri.rst',
  'platformdirs.rst',
  'pluggy.rst',
  'ply.rst',
  'polylib.rst',
  'polymake.rst',
  'polytopes_db.rst',
  'polytopes_db_4d.rst',
  'ppl.rst',
  'pplpy.rst',
  'pplpy_doc.rst',
  'primecount.rst',
  'primecountpy.rst',
  'primesieve.rst',
  'prometheus_client.rst',
  'prompt_toolkit.rst',
  'psutil.rst',
  'ptyprocess.rst',
  'pure_eval.rst',
  'py.rst',
  'pybind11.rst',
  'pybtex.rst',
  'pycosat.rst',
  'pycparser.rst',
  'pycryptosat.rst',
  'pygments.rst',
  'pygraphviz.rst',
  'pynormaliz.rst',
  'pyparsing.rst',
  'pyppeteer.rst',
  'pyproject_api.rst',
  'pyproject_hooks.rst',
  'pyproject_metadata.rst',
  'pyscipopt.rst',
  'pysingular.rst',
  'pytest.rst',
  'pytest_mock.rst',
  'pytest_xdist.rst',
  'python_build.rst',
  'python_discovery.rst',
  'python_flint.rst',
  'python_igraph.rst',
  'python_json_logger.rst',
  'pythran.rst',
  'pytz.rst',
  'pytz_deprecation_shim.rst',
  'pyx.rst',
  'pyyaml.rst',
  'pyzmq.rst',
  'qdldl_python.rst',
  'qepcad.rst',
  'qhull.rst',
  'r.rst',
  'r_jupyter.rst',
  'readline.rst',
  'referencing.rst',
  'regina.rst',
  'requests.rst',
  'rfc3339_validator.rst',
  'rfc3986_validator.rst',
  'roman_numerals.rst',
  'rpds_py.rst',
  'rpy2.rst',
  'rpy2_rinterface.rst',
  'rpy2_robjects.rst',
  'rst2ipynb.rst',
  'rubiks.rst',
  'rw.rst',
  'saclib.rst',
  'sage_docbuild.rst',
  'sage_flatsurf.rst',
  'sage_numerical_backends_coin.rst',
  'sage_numerical_backends_cplex.rst',
  'sage_numerical_backends_gurobi.rst',
  'sage_setup.rst',
  'sagemath_categories.rst',
  'sagemath_doc_html.rst',
  'sagemath_doc_pdf.rst',
  'sagemath_giac.rst',
  'sagemath_environment.rst',
  'sagemath_objects.rst',
  'sagemath_repl.rst',
  'sagenb_export.rst',
  'sagetex.rst',
  'sbcl.rst',
  'scikit_build_core.rst',
  'scip.rst',
  'scip_sdp.rst',
  'scipy.rst',
  'scs.rst',
  'semigroups.rst',
  'send2trash.rst',
  'setuptools.rst',
  'setuptools_scm.rst',
  'singular.rst',
  'singular_jupyter.rst',
  'sirocco.rst',
  'six.rst',
  'slabbe.rst',
  'snappy.rst',
  'sniffio.rst',
  'snowballstemmer.rst',
  'soplex.rst',
  'sortedcontainers.rst',
  'soupsieve.rst',
  'sphinx.rst',
  'sphinx_basic_ng.rst',
  'sphinx_copybutton.rst',
  'sphinx_inline_tabs.rst',
  'sphinxcontrib_applehelp.rst',
  'sphinxcontrib_devhelp.rst',
  'sphinxcontrib_htmlhelp.rst',
  'sphinxcontrib_jsmath.rst',
  'sphinxcontrib_qthelp.rst',
  'sphinxcontrib_serializinghtml.rst',
  'sphinxcontrib_websupport.rst',
  'sqlalchemy.rst',
  'stack_data.rst',
  'suitesparse.rst',
  'surface_dynamics.rst',
  'symengine.rst',
  'symengine_py.rst',
  'symmetrica.rst',
  'sympow.rst',
  'sympy.rst',
  'tachyon.rst',
  'tdlib.rst',
  'terminado.rst',
  'texlive.rst',
  'texlive_luatex.rst',
  'texttable.rst',
  'threejs.rst',
  'tides.rst',
  'tinycss2.rst',
  'tomli_w.rst',
  'topcom.rst',
  'tornado.rst',
  'tox.rst',
  'traitlets.rst',
  'trove_classifiers.rst',
  'types_python_dateutil.rst',
  'typing_extensions.rst',
  'tzdata.rst',
  'tzlocal.rst',
  'uri_template.rst',
  'urllib3.rst',
  'valgrind.rst',
  'vcs_versioning.rst',
  'virtualenv.rst',
  'wcwidth.rst',
  'webcolors.rst',
  'webencodings.rst',
  'websocket_client.rst',
  'wheel.rst',
  'widgetsnbextension.rst',
  'xindy.rst',
  'zeromq.rst',
  'zipp.rst',
]

foreach file : doc_sources
  doc_src += fs.copyfile(file)
endforeach

