doc_sources = [
  'conda.rst',
  'conf.py',
  'index.rst',
  'launching.rst',
  'source.rst',
  'troubles.rst',
  'source-distro.rst',
  'arch.txt',
  'arch-optional.txt',
  'arch-recommended.txt',
  'arch-develop.txt',
  'debian.txt',
  'debian-optional.txt',
  'debian-recommended.txt',
  'debian-develop.txt',
  'fedora.txt',
  'fedora-optional.txt',
  'fedora-recommended.txt',
  'fedora-develop.txt',
  'homebrew.txt',
  'homebrew-optional.txt',
  'homebrew-recommended.txt',
  'homebrew-develop.txt',
  'opensuse.txt',
  'opensuse-optional.txt',
  'opensuse-recommended.txt',
  'opensuse-develop.txt',
  'void.txt',
  'void-optional.txt',
  'void-recommended.txt',
  'void-develop.txt',
]

foreach file : doc_sources
  doc_src += fs.copyfile(file)
endforeach

