py.install_sources(
  '__init__.py',
  '__main__.py',
  'all.py',
  'check_tolerance.py',
  'control.py',
  'external.py',
  'fixtures.py',
  'forker.py',
  'marked_output.py',
  'parsing.py',
  'parsing_test.py',
  'reporting.py',
  'rif_tol.py',
  'sources.py',
  'test.py',
  'util.py',
  subdir: 'sage/doctest',
)

install_subdir('tests', install_dir: sage_install_dir / 'doctest')
