py.install_sources(
  '__init__.py',
  'backend_base.py',
  'backend_doctest.py',
  'backend_emacs.py',
  'backend_ipython.py',
  'buffer.py',
  'display_manager.py',
  'output_basic.py',
  'output_browser.py',
  'output_catalog.py',
  'output_graphics.py',
  'output_graphics3d.py',
  'output_video.py',
  'preferences.py',
  'pretty_print.py',
  'test_backend.py',
  subdir: 'sage/repl/rich_output',
)

install_data(
  'example.avi',
  'example.canvas3d',
  'example.dvi',
  'example.flv',
  'example.gif',
  'example.jpg',
  'example.mkv',
  'example.mov',
  'example.mp4',
  'example.ogv',
  'example.pdf',
  'example.png',
  'example.svg',
  'example.webm',
  'example.wmv',
  'example_jmol.spt.zip',
  'example_wavefront_scene.mtl',
  'example_wavefront_scene.obj',
  install_dir: sage_install_dir / 'repl/rich_output',
)
