name: Build Docker images and push to DockerHub

on:
  workflow_dispatch:
    # Allow to run manually

jobs:
  sagemath-dev:
    uses: ./.github/workflows/docker_hub.yml
    with:
      # Build from scratch
      dockerhub_repository: sagemath-dev
      dockerfile_target: make-build
    secrets: inherit

  sagemath:
    needs: sagemath-dev
    uses: ./.github/workflows/docker_hub.yml
    with:
      # Build from sagemath-dev
      dockerhub_repository: sagemath
      dockerfile_target: sagemath
    secrets: inherit
