#!/usr/bin/env python3

import argparse
import io
import logging
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import tokenize

from sage.cli.options import CliOptions


_ADVANCED_HELP = """\
SageMath command line options:

  --advanced        print this advanced help message
  --python         run the Python interpreter used by this Sage installation
  --python3        run the Python interpreter used by this Sage installation
  --sh             run a system shell with the Sage environment
  --ecl, --lisp    run the ECL Lisp interpreter
  --gap            run the GAP interpreter
  --gp             run the PARI/GP interpreter
  --maxima         run the Maxima interpreter
  --mwrank         run the mwrank executable
  --singular       run the Singular interpreter
  --cython         run Cython
  --preparse       preparse .sage files to .sage.py files
  --cleaner        run the Sage cleaner. (source-tree only)

Some source-tree developer options are unavailable in pip-installed sagelite.
In a full Sage source checkout, run the source-tree sage launcher for options
such as --root, --grep, or the Sage cleaner.
"""


class SageArgumentParser(argparse.ArgumentParser):
    def error(self, message):
        if message.startswith("unrecognized arguments:"):
            unknown = message.partition(":")[2].strip()
            self.exit(2, f"unknown option: {unknown}\n")
        super().error(message)


def _ecl_command() -> str:
    try:
        from sagelite_ecl.runtime import ecl_command
    except ImportError:
        return "ecl"

    command = os.fspath(ecl_command())
    if os.path.isfile(command) and os.access(command, os.X_OK):
        return command
    return "ecl"


def _shell_command() -> str:
    return os.environ.get("SHELL") or "/bin/sh"


def _python_command() -> str:
    return sys.executable


def _singular_command() -> str:
    try:
        from sage.env import SINGULAR_BIN
    except ImportError:
        return "Singular"
    return os.fspath(SINGULAR_BIN or "Singular")


def _maxima_command() -> str:
    try:
        from sage.env import MAXIMA
    except ImportError:
        return "maxima"
    return os.fspath(MAXIMA or "maxima")


def _mwrank_command() -> str:
    try:
        from sage.env import MWRANK
    except ImportError:
        return "mwrank"
    return os.fspath(MWRANK or "mwrank")


def _gap_command() -> str:
    try:
        from sage.interfaces.gap import gap_command
    except ImportError:
        return "gap"
    return gap_command(use_workspace_cache=False)[0]


def _run_command(command: str, args: list[str]) -> int:
    if any(char.isspace() for char in command) or any(char in command for char in "\"'"):
        command_line = command
        if args:
            command_line += " " + shlex.join(args)
        return subprocess.call(command_line, shell=True)
    if not os.path.isabs(command):
        sibling = Path(sys.executable).parent / command
        if sibling.is_file() and os.access(sibling, os.X_OK):
            command = os.fspath(sibling)
    return subprocess.call([command, *args])


_AUTOGEN_MSG = "# This file was *autogenerated* from the file "


def _split_coding_line(contents: str) -> tuple[str, str]:
    lines = contents.splitlines()
    for num, line in enumerate(lines[:2]):
        if re.search(r"coding[:=]\s*([-\w.]+)", line):
            coding = line + "\n"
            return coding, "\n".join(lines[:num] + lines[(num + 1):])
    return "", contents


def _line_offsets(contents: str) -> list[int]:
    offsets = [0]
    total = 0
    for line in contents.splitlines(True):
        total += len(line)
        offsets.append(total)
    return offsets


def _split_module_docstring(contents: str) -> tuple[str, str]:
    offsets = _line_offsets(contents)
    try:
        tokens = tokenize.generate_tokens(io.StringIO(contents).readline)
        for token in tokens:
            if token.type in (
                tokenize.COMMENT,
                tokenize.NL,
                tokenize.NEWLINE,
                tokenize.INDENT,
                tokenize.DEDENT,
                tokenize.ENCODING,
            ):
                continue
            if token.type == tokenize.STRING:
                line, col = token.end
                index = offsets[line - 1] + col
                return contents[:index], contents[index:]
            break
    except tokenize.TokenError:
        pass
    return "", contents


def _preparse_files(files: list[str]) -> int:
    from sage.repl.preparse import preparse_file

    for filename in files:
        input_path = Path(filename)
        output_path = input_path.with_suffix(input_path.suffix + ".py")
        if output_path.exists() and _AUTOGEN_MSG not in output_path.read_text():
            print(f"Refusing to overwrite existing non-autogenerated file {os.fspath(output_path)!r}.")
            print("Please delete or move this file manually.")
            return 1
        contents = input_path.read_text()
        coding, contents = _split_coding_line(contents)
        header, body = _split_module_docstring(contents)
        body = preparse_file(body)
        with output_path.open("w") as out:
            out.write(coding)
            out.write(header)
            out.write("\n")
            out.write(f"{_AUTOGEN_MSG}{input_path}\n")
            out.write("from sage.all_cmdline import *   # import sage library\n\n")
            out.write(body)
            out.write("\n")
    return 0


def _print_advanced_help() -> int:
    print(_ADVANCED_HELP, end="")
    return 0


def main() -> int:
    input_args = sys.argv[1:]
    if input_args and input_args[0] in ("-ecl", "--ecl", "-lisp", "--lisp"):
        return subprocess.call([_ecl_command(), *input_args[1:]])
    if input_args and input_args[0] == "--gap":
        return _run_command(_gap_command(), input_args[1:])
    if input_args and input_args[0] == "--gp":
        return _run_command("gp", input_args[1:])
    if input_args and input_args[0] == "--maxima":
        return _run_command(_maxima_command(), input_args[1:])
    if input_args and input_args[0] == "--mwrank":
        return _run_command(_mwrank_command(), input_args[1:])
    if input_args and input_args[0] == "--singular":
        return _run_command(_singular_command(), input_args[1:])
    if input_args and input_args[0] == "--cython":
        return _run_command("cython", input_args[1:])
    if input_args and input_args[0] == "--preparse":
        return _preparse_files(input_args[1:])
    if input_args and input_args[0] == "--sh":
        return subprocess.call([_shell_command(), *input_args[1:]])
    if input_args and input_args[0] in ("--python", "--python3"):
        return subprocess.call([_python_command(), *input_args[1:]])
    if input_args and input_args[0] == "--advanced":
        return _print_advanced_help()

    from sage.cli.eval_cmd import EvalCmd
    from sage.cli.interactive_shell_cmd import InteractiveShellCmd
    from sage.cli.notebook_cmd import JupyterNotebookCmd
    from sage.cli.run_file_cmd import RunFileCmd
    from sage.cli.version_cmd import VersionCmd

    parser = SageArgumentParser(
        prog="sage",
        description="If no command is given, starts the interactive interpreter where you can enter statements and expressions, immediately execute them and see their results.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        default=False,
        help="print additional information",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        default=False,
        help="do not display the banner",
    )
    parser.add_argument(
        "--simple-prompt",
        action="store_true",
        default=False,
        help="use simple prompt IPython mode",
    )

    VersionCmd.extend_parser(parser)
    JupyterNotebookCmd.extend_parser(parser)
    EvalCmd.extend_parser(parser)
    RunFileCmd.extend_parser(parser)

    if not input_args:
        return InteractiveShellCmd(CliOptions()).run()

    args = parser.parse_args(input_args)
    options = CliOptions(**vars(args))

    logging.basicConfig(level=logging.DEBUG if options.verbose else logging.INFO)

    if args.file:
        return RunFileCmd(options).run()
    if args.command:
        return EvalCmd(options).run()
    if args.notebook:
        return JupyterNotebookCmd(options).run()
    return InteractiveShellCmd(options).run()
